<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_radius" value="0.04"/>
    <xacro:property name="base_height" value="0.011"/>
    <xacro:property name="laz_radius" value="0.03"/>
    <xacro:property name="laz_height" value="0.035"/>
    <xacro:property name="mass" value="0.1">

    </xacro:property>

    <gazebo reference="laz_base">
        <material>Gazebo/Grey</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <link name="laz_base">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="${(1/12) * mass * (3 * base_radius * base_radius + base_height * base_height)}" ixy="0.0" ixz="0.0" 
                    iyy="${(1/12) * mass * (3 * base_radius * base_radius + base_height * base_height)}" iyz="0.0" 
                    izz="${(1/12) * mass * base_radius * base_radius}"/>
        </inertial>
    </link>

    <gazebo reference="laz_rot">
        <material>Gazebo/RedGlow</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>

        <!--|Crear el sensor para Gazebo-->
        <sensor type="ray" name="laz">
            <always_on>true</always_on>
            <pose>0 0 ${laz_height/4} 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>

            <ray>
                <scan>
                    <horizontal>
                        <samples>250</samples>
                        <resolution>1</resolution>
                        <min_angle>-${pi}</min_angle>
                        <max_angle>${pi}</max_angle>
                    </horizontal>
                    <!-- <vertical>
                        <samples>1</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.15</min_angle>
                        <max_angle>0.15</max_angle>
                    </vertical> -->
                </scan>
                <range>
                    <min>0.05</min>
                    <max>15</max>
                    <resolution>0.02</resolution>
                </range>
            </ray>

            <!--*AÃ±adir Ruido-->
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
            </noise>

            <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_laser.so">
                <topicName>/my_robot/laser/scan</topicName>
                <frameName>laz_rot</frameName>
                <updateRate>40.0</updateRate>
                <minRange>0.08</minRange>
                <maxRange>15.0</maxRange>
                <minIntensity>0.0</minIntensity>
                <maxIntensity>100.0</maxIntensity>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </plugin>
        </sensor>

    </gazebo>

    <link name="laz_rot">
        <visual>
            <geometry>
                <cylinder radius="${laz_radius}" length="${laz_height}"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${laz_radius}" length="${laz_height}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="${(1/12) * mass * (3 * laz_radius * laz_radius + laz_height * laz_height)}" ixy="0.0" ixz="0.0" 
                    iyy="${(1/12) * mass * (3 * laz_radius * laz_radius + laz_height * laz_height)}" iyz="0.0" 
                    izz="${(1/12) * mass * (laz_radius * laz_radius)}"/>
        </inertial>
    </link>

    <joint name="lazRot" type="continuous">
        <parent link="laz_base"/>
        <child link="laz_rot"/>
        <axis xyz="0.0 0.0 1.0"/>
        <origin xyz="0.0 0.0 ${base_height}"/>
        <dynamics friction="0.1"/>    
    </joint>

</robot>