Training:
# Lidar config for the observation space
  robot_name: R2
  min_distance: 0.15
  max_distance: 12.0
  num_lidar_measurements: 281
# Task config
  x_goal: 2.5
  y_goal: -2.5
  timestep_limit_per_episode: 4000
# Condiciones para calificar el aprendizaje del agente
  mean_reward_bound: 1000
  number_of_rewards_to_average: 10
# Hiperparámetros de entrenamiento
  gamma: 0.9
  batch_size: 64
  learning_rate: 0.0001
  eps_start: 1.0
  eps_decay: 0.999985
  eps_min: 0.02
  exp_replay_size: 20000
  sync_target_network: 1000
  #x: -9.0, y: 9.0
  # 8000 para considerar que aprendió
