Training:
# Lidar config for the observation space
  robot_name: R2
  min_distance: 0.15
  max_distance: 12.0
  num_lidar_measurements: 281
# Training config
  x_goal: -4.0
  y_goal: 2.0
  timestep_limit_per_episode: 10000
  #x: -9.0, y: 9.0
