Training:
# Lidar config for the observation space
  robot_name: R2
  min_distance: 0.15
  max_distance: 12.0
  num_lidar_measurements: 281
# Task config
  goals_axis_x: [1.0, 1.5]
  goals_axis_y: [0.0, 1.0]
  # x_goal: -1.5
  # y_goal: 1.5
  threshold_goal: 0.2
  timestep_limit_per_episode: 1000
# Condiciones para calificar el aprendizaje del agente
  mean_reward_bound: 1200
  number_of_rewards_to_average: 10
# Hiperparámetros de entrenamiento
  gamma: 0.9
  batch_size: 64
  learning_rate: 0.0001
  eps_start: 0.02
  eps_decay: 0.99987
  eps_min: 0.02
  exp_replay_size: 40000
  sync_target_network: 2000
  #x: -9.0, y: 9.0
  # 8000 para considerar que aprendió
